config/routes.rb
Rails.application.routes.draw do

  
    
  resource :admin, controller: 'admin' do
    
    post 'login', controller: 'admin', action: 'authenticate', on: :collection
    post 'signup', controller: 'admin', action: 'register', on: :collection
    post 'forgot', controller: 'admin', action: 'reset', on: :collection
    
    resource :settings do 
      resource :profiles, except: [:new, :edit, :create, :destroy]
      resources :users
      resources :roles do
        post 'sort', on: :collection
      end
      get ':action', on: :collection, as: 'action'
    end
    
    resource :contents do
      resources :banners do
        post 'sort', on: :collection
      end
      
      resources :comics do
        resources :episodes do
          post 'sort', on: :collection
          resources :images, only: [:create, :destroy] do
            post 'sort', on: :collection
          end
        end
        post 'sort', on: :collection
      end
      
      resources :news do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :galleries do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :events do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end

      resources :categories do
        post 'sort', on: :collection
      end
    end

    resource :store, controller: 'store' do
      resources :products do 
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
        resources :product_items, as: 'items' do
          post 'sort', on: :collection
        end
      end
      
      resources :orders, except: [:new, :create, :destroy] do
        post 'cancel/:id', on: :collection, action: 'cancel', as: 'cancel'
        post 'revert/:id', on: :collection, action: 'revert', as: 'revert'
        post 'process/:id', on: :collection, action: 'do_process', as: 'process'
        get ':id/:action', on: :collection, as: 'action', id: nil
      end
      
      resources :collections do
        post 'sort', on: :collection
        get ':action', on: :collection, as: 'action'
      end
      
      resources :customers
    end

    resources :tags do
      post 'sort', on: :collection
    end

    resource :mailings do
      resources :campaigns, controller: 'mailing_campaigns'
      resources :lists, controller: 'mailing_lists'
    end
    
    resources :dashboards
        
    
    get ':action', controller: 'admin', on: :collection, as: 'action'
  end  
  
  resource :pages do
    resources :comics
    resources :episodes
  end
  
  post 'mailing_lists/signup', controller: 'mailing_lists', action: 'signup'

  get 'catalogs', controller: 'catalogs', as: 'catalogs_all', action: 'comics'
  get 'catalogs/:comic', controller: 'catalogs', comic: nil, as: 'catalogs_comic', action: 'comic'
  get 'catalogs/episode/:episode', controller: 'catalogs', episode: nil, as: 'catalogs_comic_episode', action: 'episode'
  
  get ':controller/:action/:id'
  
  get '/', controller: 'pages', action: 'show'  
end

app/views/admin/_forgot_form.html.erb
<!-- BEGIN FORGOT PASSWORD FORM -->
<%= form_tag forgot_admin_url, method: :post, class: "forget-form", style: style do %>
	<h3>Forget Password ?</h3>
	<p>Enter your e-mail address below to reset your password.</p>
	<div class="form-group">
		<input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
	</div>
	<div class="form-actions">
		<button type="button" id="back-btn" class="btn btn-default">Back</button>
		<button type="submit" class="btn btn-success uppercase pull-right">Submit</button>
	</div>
<% end %>
<!-- END FORGOT PASSWORD FORM -->

app/views/admin/_login_form.html.erb
<!-- BEGIN LOGIN FORM -->
<%= form_tag login_admin_url, method: :post, class: "login-form", style: style do %>
	<h3 class="form-title">Sign In</h3>
	<div class="alert alert-danger display-hide">
		<button class="close" data-close="alert"></button>
		<span>Enter any username and password. </span>
	</div>
	<div class="form-group">
		<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
		<label class="control-label visible-ie8 visible-ie9">Email / Username</label>
		<%= email_field_tag 'user[email_username]', nil, {class: "form-control form-control-solid placeholder-no-fix", placeholder: "Email / Username",  autocomplete: "off"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">Password</label>
		<%= password_field_tag 'user[password]', nil, {class: "form-control form-control-solid placeholder-no-fix", placeholder: "Password",  autocomplete: "off"} %>
	</div>
	<div class="form-actions">
	  <%= button_tag 'Login', name: 'login', class: "btn btn-success uppercase" %>
		<label class="rememberme check">
		<input type="checkbox" name="remember" value="1"/>Remember </label>
		<a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
	</div>
	<div class="create-account">
		<p>
			<a href="javascript:;" id="register-btn" class="uppercase">Create an account</a>
		</p>
	</div>
<% end %>
<!-- END LOGIN FORM -->

app/views/admin/_registration_form.html.erb
<!-- BEGIN REGISTRATION FORM -->
<%= form_tag signup_admin_url, method: :post, class: "register-form", multipart: true, style: style do %>
	<h3>Sign Up</h3>
	<p class="hint">
		 Enter your account details below:
	</p>
	<div class="form-group">
		<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
		<label class="control-label visible-ie8 visible-ie9">Email</label>
		<%= email_field_tag 'user[email]', nil, {class: "form-control placeholder-no-fix required", placeholder: "Email"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">Username</label>
    <%= text_field_tag 'user[username]', nil, {class: "form-control placeholder-no-fix required", placeholder: "Username",  autocomplete: "off"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">Password</label>
		<%= password_field_tag 'user[password]', nil, {class: "form-control placeholder-no-fix required", placeholder: "Password", autocomplete: "off"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
		<%= password_field_tag 'user[confirm_password]', nil, {class: "form-control placeholder-no-fix required", placeholder: "Re-type Your Password", autocomplete: "off"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">First Name</label>
    <%= text_field_tag 'user[first_name]', nil, {class: "form-control placeholder-no-fix", placeholder: "First Name",  autocomplete: "off"} %>
	</div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">Last Name</label>
    <%= text_field_tag 'user[last_name]', nil, {class: "form-control placeholder-no-fix required", placeholder: "Last Name",  autocomplete: "off"} %>
	</div>
	<div class="form-group margin-top-20 margin-bottom-20">
		<label class="check">
		<input type="checkbox" name="tnc"/> I agree to the <a href="javascript:;">
		Terms of Service </a>
		& <a href="javascript:;">
		Privacy Policy </a>
		</label>
		<div id="register_tnc_error">
		</div>
	</div>
	<div class="form-actions">
		<%= button_tag 'Back', name: 'back', class: "btn btn-default", id: "register-back-btn" %>
		<%= button_tag 'Submit', name: 'sign_up', class: "btn btn-success uppercase pull-right", id: "register-submit-btn" %>  
	</div>
<% end %>
<!-- END REGISTRATION FORM -->

app/views/admin/forgot.html.erb
<!-- BEGIN LOGIN -->
<div class="content"> 
  <%= render partial: 'admin/login_form', locals: {style: 'display:none;'} %>

  <%= render partial: 'admin/forgot_form', locals: {style: 'display:inline;'} %>
  
  <%= render partial: 'admin/registration_form', locals: {style: 'display:none;'} %>
</div>
<!-- END LOGIN -->

app/views/admin/help.html.erb
<div class="modal-header">
    <h1 class="text-center">Help</h1>
    <% if flash[:error] %><div class="error"><%= flash[:error] %></div><% end %>
</div>
<div class="modal-body">
  <div class="success">
    <ul>
    <h3><li>Help #1</li></h3>
    <h3><li>Help #2</li></h3>
    <h3><li>Help #3</li></h3>
    <h3><li>Help #4</li></h3>
    </ul>
  </div>
  <div class="form-group">
    <span class="pull-right"><%= link_to 'Go Back', admin_url %></span>
  </div>
</div>

app/views/admin/login.html.erb
<!-- BEGIN LOGIN -->
<div class="content">
  <%= render partial: 'admin/login_form', locals: {style: 'display:inline;'} %>

  <%= render partial: 'admin/forgot_form', locals: {style: 'display:none;'} %>
  
  <%= render partial: 'admin/registration_form', locals: {style: 'display:none;'} %>
</div>
<!-- END LOGIN -->

app/views/admin/registration.html.erb
<!-- BEGIN LOGIN -->
<div class="content"> 
  <%= render partial: 'admin/login_form', locals: {style: 'display:none;'} %>

  <%= render partial: 'admin/forgot_form', locals: {style: 'display:none;'} %>
  
  <%= render partial: 'admin/registration_form', locals: {style: 'display:inline;'} %>
</div>
<!-- END LOGIN -->