config/routes.rb
Rails.application.routes.draw do

  
    
  resource :admin, controller: 'admin' do
    
    post 'login', controller: 'admin', action: 'authenticate', on: :collection
    post 'signup', controller: 'admin', action: 'register', on: :collection
    post 'forgot', controller: 'admin', action: 'reset', on: :collection
    
    resource :settings do 
      resource :profiles, except: [:new, :edit, :create, :destroy]
      resources :users
      resources :roles do
        post 'sort', on: :collection
      end
      get ':action', on: :collection, as: 'action'
    end
    
    resource :contents do
      resources :banners do
        post 'sort', on: :collection
      end
      
      resources :comics do
        resources :episodes do
          post 'sort', on: :collection
          resources :images, only: [:create, :destroy] do
            post 'sort', on: :collection
          end
        end
        post 'sort', on: :collection
      end
      
      resources :news do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :galleries do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :events do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end

      resources :categories do
        post 'sort', on: :collection
      end
    end

    resource :store, controller: 'store' do
      resources :products do 
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
        resources :product_items, as: 'items' do
          post 'sort', on: :collection
        end
      end
      
      resources :orders, except: [:new, :create, :destroy] do
        post 'cancel/:id', on: :collection, action: 'cancel', as: 'cancel'
        post 'revert/:id', on: :collection, action: 'revert', as: 'revert'
        post 'process/:id', on: :collection, action: 'do_process', as: 'process'
        get ':id/:action', on: :collection, as: 'action', id: nil
      end
      
      resources :collections do
        post 'sort', on: :collection
        get ':action', on: :collection, as: 'action'
      end
      
      resources :customers
    end

    resources :tags do
      post 'sort', on: :collection
    end

    resource :mailings do
      resources :campaigns, controller: 'mailing_campaigns'
      resources :lists, controller: 'mailing_lists'
    end
    
    resources :dashboards
        
    
    get ':action', controller: 'admin', on: :collection, as: 'action'
  end  
  
  resource :pages do
    resources :comics
    resources :episodes
  end
  
  post 'mailing_lists/signup', controller: 'mailing_lists', action: 'signup'

  get 'catalogs', controller: 'catalogs', as: 'catalogs_all', action: 'comics'
  get 'catalogs/:comic', controller: 'catalogs', comic: nil, as: 'catalogs_comic', action: 'comic'
  get 'catalogs/episode/:episode', controller: 'catalogs', episode: nil, as: 'catalogs_comic_episode', action: 'episode'
  
  get ':controller/:action/:id'
  
  get '/', controller: 'pages', action: 'show'  
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  include Sort
  include UrlName
  
  has_many :episodes, dependent: :destroy
  belongs_to :category
  
  has_many :tag_relations, as: :content, inverse_of: :content
  has_many :tags, through: :tag_relations
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/system/defaults/no_image.png" #600 x 200 px
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # validates :image, dimensions: { width: 1366, height: 450 }

  # BANNER HEADER IMAGE
  has_attached_file :banner_image, :styles => { :medium => "682x225>", :small => "341x113>", :thumb => "170x56>" }, :default_url => "/system/defaults/no_image.png"
  validates_attachment_content_type :banner_image, :content_type => /\Aimage\/.*\Z/
  validates :banner_image, dimensions: { width: 1366, height: 450 }
  
  validates_presence_of :name
  
  scope :active, -> { where("publish_at < NOW() AND (retract_at IS NULL OR retract_at > NOW())") }
  
  before_create :initialize_sort!
  before_save :set_tags
  
  attr_accessor :tag_ids

  class << self
    def find_by_url_name(comic_url_name)
      find(get_identifier(comic_url_name))    
    end    
  end

  def main_image
    image.exists? || (episodes.order(:sort).first && episodes.order(:sort).first.image)
  end
  
  def category_name
    category ? category.name : ''
  end
  
  def url_name
    id.to_s + SEPARATOR + self.class.normalize_name(name)
  end
  
  def episode_image
    episodes.empty? ? image : episodes.first.image
  end
  
    
  protected

    def set_tags
      return if tag_ids.nil?
      self.tag_relations.to_a.each {|tr| tag_ids.include?(tr.tag_id.to_s) ? 
                                          tag_ids.delete(tr.tag_id.to_s) :
                                          tr.destroy}
      tag_ids.each do |tag_id|
        next if tag_id.blank?
        self.tags << Tag.find(tag_id)
      end
    end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  layout 'admin'
  
  def index
    @comics = Comic.all.order(:sort)
  end
  
  def new
    @comic = Comic.new
  end
  
  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      flash[:success] = 'Comic Create success!'
      redirect_to edit_admin_contents_comic_url(id: @comic.id) and return
    end
    @errors = @comic.errors
    flash[:error] = "We're sorry, we cannot create the comic at the moment"
    render template: 'comics/new'
  end

  def edit
    @comic = Comic.find(params[:id])
  end
  
  def update
    @comic = Comic.find(params[:id])
    if @comic.update_attributes(comic_params)
      flash[:success] = 'Comic Update success!'
      redirect_to edit_admin_contents_comic_url and return
    end
    @errors = @comic.errors
    flash[:error] = "We're sorry, we cannot update the comic at the moment"
    render template: 'comics/edit'
  end
  
  def destroy
    Comic.find(params[:id]).destroy
    redirect_to admin_contents_comics_url
  end
    
  def sort
    Comic.sort!(params[:comic][:sort])
    flash[:success] = 'Comic Sort success!'
    redirect_to admin_contents_comics_url
  end
  
  protected
    
    def comic_params
      params.require(:comic).permit!
    end

end

app/helpers/comics_helper.rb
module ComicsHelper
  def comic_options
    Comic.all.order(:sort).collect {|c| [c.name, c.id]}
  end
  
  def comics(*args)
    options = default_options(args.first)
    
    case options[:mode]
    when 'all'
      all_comics(Comic.all.active, options)
    when 'comic'
      comic_episodes(options[:comic], options)
    when 'related'
      related_comics(options[:episode], options)
    else
      '' #Episode.all.active.limit(5)
    end
    
  end

  def all_comics(comics, options)
    str = ''
    comics.each_with_index do |comic, index|
      str << '<div class="clearfix visible-xs-block"></div>' if (index % 3) == 0
      str << '<div class="clearfix visible-md-block"></div>' if (index % 5) == 0
      str << '<div class="col-md-15 col-xs-4">'
      str << '<div class="comicBox">'
      str << comic_item(comic, options)
      str << '</div>'
      str << '</div>'
    end
    
    raw(str)
  end

  def comic_episodes(comic, options)
    str = ''
    comic.episodes.each_with_index do |episode, index|
      str << '<div class="row episode">'
      str << episode_item_url(episode, options)
      str << episode_item_title(episode, options)
      str << episode_item_likes(episode, options)
      str << episode_item_date(episode, options)
      str << '</div>'
			str << '<hr/>'
    end
    
    raw(str)
  end
  
  def related_comics(episode, options)
    str = ''
    episode.related_comics[0..4].each do |comic|
      str << '<div class="col-md-15 col-xs-12">'
      str << '<div class="comicBox">'
      str << comic_item(comic, options)
      str << '</div>'
      str << '</div>'
    end
    
    raw(str)
  end
  
  protected
  
    def comic_item(comic, options)
      img_str = comic_item_img(comic, options)
      str = link_to(raw(img_str), catalogs_comic_url(comic: comic.url_name), class: 'thumbLink')
      str << raw(comic_item_info(comic, options))
      str
    end
    
    def comic_item_img(comic, options)
      str = '<div class="thumb-overlay"></div>'
      str << image_tag(comic.episode_image.url, class: "img-responsive")
      str
    end
        
    def comic_item_info(comic, options)
      str = '<div class="infoText">'
  		str << '<div class="genre"><small>'
  		str << comic.category_name
  		str << '</small></div>'
  		comic_title = '<div class="comicTitle">'
  		comic_title << comic.name
  		comic_title << '</div>'
  		str << link_to(raw(comic_title), catalogs_comic_url(comic: comic.url_name))
  		str << '<div class="creatorName">Alex Irzaqi</div>'
  		str << '</div>'
  		str
    end
  
    def episode_item_url(episode, options)
      str = '<div class="col-xs-2">'
      img_str = episode_item_img(episode, options)
      str << link_to(raw(img_str), catalogs_comic_episode_url(episode: episode.url_name), class: 'thumbLink')
      str << '</div>'
    end
    
    def episode_item_title(episode, options)
      str = '<div class="col-xs-4">'
      title_str = '<div class="comicTitle">'
      title_str << episode.name
      title_str << '</div>'
      str << link_to(raw(title_str), catalogs_comic_episode_url(episode: episode.url_name))
      str << '</div>'
    end
    
    def episode_item_img(episode, options)
      str = '<div class="thumb-overlay"></div>'
      str << image_tag(episode.image.url, class: "img-responsive")
      str
    end

    def episode_item_likes(episode, options)
      str = '<div class="col-xs-4">'
			str << '<div class="comicLikes">'
			5.times do |i|
			  str << '<i class="fa fa-star'
			  str << '-o' if i >= episode.rating
			  str << '"></i>'
		  end
			str << '</div>'
			str << '</div>'
		end
		
    def episode_item_date(episode, options)
      str = '<div class="col-xs-2">'
			str << '<i class="comicDate">'
			str << '</i>'
			str << '</div>'
    end
    
end

app/views/comics/_form.html.erb
<div class="form-body">
	<div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:name].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Name</label>
		<div class="col-md-9">
      <%= f.text_field :name, class: "form-control#{' error' unless @comic.errors[:name].blank?}", placeholder: 'Enter Name', id: 'form_control_1' %>			
      <div class="form-control-focus"></div>
		</div>
	</div>
	<div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:description].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Description</label>
		<div class="col-md-9">
      <%= f.text_field :description, class: "form-control#{' error' unless @comic.errors[:description].blank?}", placeholder: 'Enter Description', id: 'form_control_1' %>			
      <div class="form-control-focus"></div>
		</div>
	</div>
	<div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:category_id].blank? %>">  	
		<label class="col-md-3 control-label" for="form_control_1">Category</label>
		<div class="col-md-9">
		  <%= f.select :category_id, category_options, {selected: @comic.category_id}, {class: "form-control input-xlarge select2me", id: 'form_control_1'} %>
			<div class="form-control-focus"></div>
		</div>
	</div>
	<div class="form-group form-md-line-input">
	  <label class="col-md-3 control-label" for="form_control_1">Tags</label>
		<div class="col-md-9">
      <%= f.select :tag_ids, tagging_options, {selected: @comic.tags.collect(&:id)}, {class: "form-control input-xlarge select2me", multiple: true, id: 'form_control_1'} %>
			<div class="form-control-focus"></div>
		</div>
	</div>
  <div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:publish_at].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Publish Time</label>
		<div class="col-md-5">
			<div class="input-group date form_datetime">
				<%= f.text_field :publish_at, value: datetime_value(@comic.publish_at), class: "form-control#{' error' unless @comic.errors[:publish_at].blank?}", size: 16, placeholder: 'Select Publish Time' %>	
				<span class="input-group-btn">
				<button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
				</span>
			</div>
			<!-- /input-group -->
		</div>
	</div>
  <div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:retract_at].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Retract Time</label>
		<div class="col-md-5">
			<div class="input-group date form_datetime">
				<%= f.text_field :retract_at, value: datetime_value(@comic.retract_at), class: "form-control#{' error' unless @comic.errors[:retract_at].blank?}", size: 16, placeholder: 'Select Retract Time' %>	
				<span class="input-group-btn">
				<button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
				</span>
			</div>
			<!-- /input-group -->
		</div>
	</div>
	<!--
	<div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:image].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Image Upload</label>
 		<div class="col-md-5 fileinput fileinput-<%= @comic.image.exists? ? 'exists' : 'new' %>" data-provides="fileinput">
			<div class="fileinput-<%= @comic.image.exists? ? 'exists' : 'new' %> thumbnail">
			  <%= image_tag @comic.image.url(:medium) %>
			</div>
      	<div class="fileinput-preview fileinput-<%= !@comic.image.exists? ? 'exists' : 'new' %> thumbnail"></div>
			<div class="fileinput-previewimg fileinput-preview thumbnail" style="display:none;"></div>
      <div id="fileinput-noimage" class="fileinput-noimage thumbnail" style="display:none;">
			  <%= image_tag @comic.image.options[:default_url] %>
			</div>
			<div>
				<span class="btn default btn-file">
  				<span class="fileinput-new fileinput-noimage">Select image </span>
  				<span class="fileinput-exists fileinput-preview">Change </span>
				  <%= f.file_field :image, as: :file, class: "form-control#{' error' unless @comic.errors[:image].blank?}" %>
				</span>
				<a href="javascript:;" class="btn default fileinput-exists fileinput-preview" data-dismiss="fileinput">Remove </a>
			</div>
		</div>
	</div>
	-->
	<div class="form-group form-md-line-input<%' has-error' unless @comic.errors[:banner_image].blank? %>">
		<label class="col-md-3 control-label" for="form_control_1">Banner Image Upload</label>
 		<div class="col-md-5 fileinput fileinput-<%= @comic.banner_image.exists? ? 'exists' : 'new' %>" data-provides="fileinput">
			<div class="fileinput-<%= @comic.banner_image.exists? ? 'exists' : 'new' %> thumbnail">
			  <%= image_tag @comic.banner_image.url(:medium) %>
			</div>
<!--			<div class="fileinput-preview fileinput-<%= !@comic.banner_image.exists? ? 'exists' : 'new' %> thumbnail"></div> -->
			<div class="fileinput-previewimg fileinput-preview thumbnail" style="display:none;"></div>
      <div id="fileinput-noimage" class="fileinput-noimage thumbnail" style="display:none;">
			  <%= image_tag @comic.banner_image.options[:default_url] %>
			</div>
			<div>
				<span class="btn default btn-file">
  				<span class="fileinput-new fileinput-noimage">Select image </span>
  				<span class="fileinput-exists fileinput-preview">Change </span>
				  <%= f.file_field :banner_image, as: :file, class: "form-control#{' error' unless @comic.errors[:banner_image].blank?}" %>
				</span>
				<a href="javascript:;" class="btn default fileinput-exists fileinput-preview" data-dismiss="fileinput">Remove </a>
			</div>
		</div>
	</div>
</div>

app/views/comics/_header.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li><i class="fa fa-home"></i>Home<i class="fa fa-angle-right"></i></li>
		<li>Contents<i class="fa fa-angle-right"></i></li>
		<li>Comics
		<% breadcrumbs.each do |b| %>
		  <i class="fa fa-angle-right"></i></li>
		  <li><%= b %>
		<% end if breadcrumbs %>
		</li>
	</ul>
</div>
<!-- END PAGE HEADER-->
<br />

<%= render partial: 'layouts/messages' %>

app/views/comics/edit.html.erb
<%= render partial: 'comics/header', locals: {breadcrumbs: [@comic.name]} %>

<%= form_for @comic, {url: admin_contents_comic_url, role: 'form', method: 'put', multipart: true, html: {class: 'form-horizontal'}} do |f| %>

<div class="row">
  <div class="col-md-offset-7 col-md-5">
    <%= link_to 'Episodes', admin_contents_comic_episodes_url(comic_id: params[:id]), class: "btn btn-primary" %>
    <%= button_tag 'Update', type: 'submit', class: "btn btn-primary green" %>
    <%= button_tag 'Reset', class: "btn btn-default", type: 'reset' %>
  </div>
</div>

<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet">
			<div class="portlet-body form">
          
          <%= render partial: 'form', locals: {f: f} %>

			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>
<!-- END PAGE CONTENT-->
<% end %>

app/views/comics/index.html.erb
    <%= render partial: 'comics/header', locals: {breadcrumbs: []} %>
    
    <%= form_tag  sort_admin_contents_comics_url, {role: 'form', method: 'post'} do |f| %>
    
  	<div class="row">
      <div class="col-md-offset-9 col-md-3">
        <%= link_to 'Add', new_admin_contents_comic_url, alt: "Add", class: "btn btn-primary green" %>
        <%= button_tag 'Sort', type: 'submit', class: "btn btn-default" %>
      </div>
    </div>
    
    <!-- BEGIN PAGE CONTENT-->
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN SAMPLE TABLE PORTLET-->
				<div class="portlet">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-rocket"></i>Comics
						</div>
						<div class="tools">
						  <a class="fullscreen" href="javascript:;" data-original-title="" title=""></a>
         			<a href="javascript:;" class="collapse"></a>
						</div>
					</div>
					<div class="portlet-body">
						<div class="table-scrollable">
							<table class="table table-striped table-bordered table-advance table-hover">
							<thead>
							<tr>
								<th class="col-md-1"><i class="fa fa-sort"></i> Sort</th>
								<th><i class="fa fa-photo"></i> Banner Image</th>
								<th><i class="fa fa-info"></i> Name</th>
								<!--th><i class="fa fa-file-text-o"></i> Description</th-->
								<th><i class="fa fa-plus-square-o"></i> Episodes</th>
								<th class="col-md-5">&nbsp;</th>
							</tr>
							</thead>
							<tbody>
							  <% @comics.each do |comic| %>
							  <%= hidden_field_tag "comic[sort][#{comic.id}][old]", comic.sort %>
							  <tr>
  								<td class="col-md-1"><%= text_field_tag "comic[sort][#{comic.id}][new]", comic.sort, class: 'form-control-size', placeholder: 'Sort #', size: 3, maxlength: 3 %></td>
  								<td><%= image_tag comic.banner_image.url(:thumb) %></td>
                  <td><%= comic.name %></td>
                  <!--td><%= comic.description %></td-->
                  <td><%= comic.episodes.size %></td>
                  <td class="col-md-5">
                    <%= link_to raw('<i class="icon-pencil"> Edit</i>'), edit_admin_contents_comic_url(id: comic.id), class: "btn btn-warning btn-xs" %>
                    <%= link_to raw('<i class="icon-trash"> Delete</i>'), admin_contents_comic_url(id: comic.id), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure you want to delete this comic?" } %>
                    <%= link_to raw('<i class="icon-eye"> View Episodes</i>'), admin_contents_comic_episodes_url(comic_id: comic.id), class: "btn btn-primary btn-xs" %>
                  </td>
  							</tr>
							  <% end %>
							</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- END SAMPLE TABLE PORTLET-->
			</div>
		</div>
		<!-- END PAGE CONTENT-->
  	
		<% end %>

app/views/comics/new.html.erb
  <%= render partial: 'comics/header', locals: {breadcrumbs: ["New"]} %>

  <%= form_for @comic, {url: admin_contents_comics_url, role: 'form', method: 'post', multipart: true, html: {class: 'form-horizontal'}} do |f| %>
  
  <div class="row">
    <div class="col-md-offset-9 col-md-3">
      <%= button_tag 'Create', type: 'submit', class: "btn btn-default green" %>
      <%= button_tag 'Reset', class: "btn btn-default", type: 'reset' %>
    </div>
  </div>

  <!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet">
				<div class="portlet-body form">
            
            <%= render partial: 'form', locals: {f: f} %>

				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
  <!-- END PAGE CONTENT-->
	<% end %>