config/routes.rb
Rails.application.routes.draw do

  
    
  resource :admin, controller: 'admin' do
    
    post 'login', controller: 'admin', action: 'authenticate', on: :collection
    post 'signup', controller: 'admin', action: 'register', on: :collection
    post 'forgot', controller: 'admin', action: 'reset', on: :collection
    
    resource :settings do 
      resource :profiles, except: [:new, :edit, :create, :destroy]
      resources :users
      resources :roles do
        post 'sort', on: :collection
      end
      get ':action', on: :collection, as: 'action'
    end
    
    resource :contents do
      resources :banners do
        post 'sort', on: :collection
      end
      
      resources :comics do
        resources :episodes do
          post 'sort', on: :collection
          resources :images, only: [:create, :destroy] do
            post 'sort', on: :collection
          end
        end
        post 'sort', on: :collection
      end
      
      resources :news do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :galleries do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :events do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end

      resources :categories do
        post 'sort', on: :collection
      end
    end

    resource :store, controller: 'store' do
      resources :products do 
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
        resources :product_items, as: 'items' do
          post 'sort', on: :collection
        end
      end
      
      resources :orders, except: [:new, :create, :destroy] do
        post 'cancel/:id', on: :collection, action: 'cancel', as: 'cancel'
        post 'revert/:id', on: :collection, action: 'revert', as: 'revert'
        post 'process/:id', on: :collection, action: 'do_process', as: 'process'
        get ':id/:action', on: :collection, as: 'action', id: nil
      end
      
      resources :collections do
        post 'sort', on: :collection
        get ':action', on: :collection, as: 'action'
      end
      
      resources :customers
    end

    resources :tags do
      post 'sort', on: :collection
    end

    resource :mailings do
      resources :campaigns, controller: 'mailing_campaigns'
      resources :lists, controller: 'mailing_lists'
    end
    
    resources :dashboards
        
    
    get ':action', controller: 'admin', on: :collection, as: 'action'
  end  
  
  resource :pages do
    resources :comics
    resources :episodes
  end
  
  post 'mailing_lists/signup', controller: 'mailing_lists', action: 'signup'

  get 'catalogs', controller: 'catalogs', as: 'catalogs_all', action: 'comics'
  get 'catalogs/:comic', controller: 'catalogs', comic: nil, as: 'catalogs_comic', action: 'comic'
  get 'catalogs/episode/:episode', controller: 'catalogs', episode: nil, as: 'catalogs_comic_episode', action: 'episode'
  
  get ':controller/:action/:id'
  
  get '/', controller: 'pages', action: 'show'  
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  include Sort
  include UrlName
  
  belongs_to :comic
  
  has_many :images, as: :content, inverse_of: :content, dependent: :destroy

  # NORMAL THUMBNAIL IMAGE
  has_attached_file :image, :styles => { :medium => "200x200>", :small => "100x100>", :thumb => "50x50>" }, :default_url => "/system/defaults/no_image.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # validates :image, dimensions: { width: 400, height: 400 }
  
  # LATEST BANNER IMAGE
  has_attached_file :banner_image, :styles => { :medium => "300x100>", :small => "150x50>", :thumb => "75x25>" }, :default_url => "/system/defaults/no_image.png"
  validates_attachment_content_type :banner_image, :content_type => /\Aimage\/.*\Z/
  validates :banner_image, dimensions: { width: 600, height: 200 }

  validates_presence_of :name
  
  scope :sort, -> { order(:sort) }
  scope :premium, -> { where("1=1") }
  scope :popular, -> { where("1=1").order(publish_at: 'desc') } #TODO
  scope :latest, -> { where("episodes.banner_image_file_name IS NOT NULL").order(:publish_at) }
  scope :active, -> { where("episodes.publish_at < NOW() AND (episodes.retract_at IS NULL OR episodes.retract_at > NOW())").includes(:comic).where("comics.publish_at < NOW() AND (comics.retract_at IS NULL OR comics.retract_at > NOW())").references(:comic) }
  
  before_create :initialize_sort!
  
  class << self
    def find_by_url_name(episode_url_name)
      find(get_identifier(episode_url_name))
    end    
  end
  
  # def image
  #   (images.order(:sort).first && images.order(:sort).first.image)
  # end  
  
  def url_name
    id.to_s + SEPARATOR + self.class.normalize_name(comic.name) + SEPARATOR + self.class.normalize_name(name)
  end
  
  def sort_group_by; {:comic_id => comic_id}; end
  
  def rating
    2.43.floor
  end
  
  def first?
    sort == 1
  end
  
  def last?
    sort == comic.episodes.last.sort
  end
  
  def previous
    Episode.where(sort: sort-1, comic_id: comic.id).first || self
  end
  
  def next
    Episode.where(sort: sort+1, comic_id: comic.id).first || self
  end
  
  def related_comics
    Comic.where("id != #{id}")
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  layout 'admin'

  def index
    @comic = Comic.find(params[:comic_id])
    @episodes = @comic.episodes.order(:sort)
  end
  
  def new
    @comic = Comic.find(params[:comic_id])
    @episode = Episode.new
  end
  
  def create
    @comic = Comic.find(params[:comic_id])
    @episode = Episode.new(episode_params)
    if @episode.save
      flash[:success] = 'Episode Create success!'
      redirect_to edit_admin_contents_comic_episode_url(id: @episode.id) and return
    end
    @errors = @episode.errors
    flash[:error] = "We're sorry, we cannot create the episode at the moment"
    render template: 'episodes/new'
  end
  
  def edit
    @comic = Comic.find(params[:comic_id])
    @episode = Episode.where(id: params[:id], comic_id: params[:comic_id]).first
  end
    
  def update
    @episode = Episode.find(params[:id])
    @episode.image.clear if episode_params[:image].is_a?(String) && episode_params[:image].empty?
    @episode.banner_image.clear if episode_params[:banner_image].is_a?(String) && episode_params[:banner_image].empty?
    if @episode.update_attributes(episode_params)
      @comic = @episode.comic
      flash[:success] = 'Episode Update success!'
      redirect_to edit_admin_contents_comic_episode_url(comic_id: @episode.comic_id) and return
    end
    @comic = @episode.comic
    @errors = @episode.errors
    flash[:error] = "We're sorry, we cannot update the episode at the moment"
    render template: 'episodes/edit'
  end
  
  def destroy
    Episode.find(params[:id]).destroy
    redirect_to admin_contents_comic_episodes_url
  end
  
  def sort
    Episode.sort!(params[:episode][:sort])
    flash[:success] = 'Episode Sort success!'
    redirect_to admin_contents_comic_episodes_url
  end
  
  protected
    
    def episode_params
      params.require(:episode).permit!
    end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def episodes(*args)
    options = default_options(args.first)
    
    case options[:mode]
    when 'latest'
      latest_episodes(Episode.all.active.latest.limit(4), options)
    when 'popular'
      popular_episodes(Episode.all.active.popular.limit(5), options)
    when 'premium'
      premium_episodes(Episode.all.active.premium.limit(4), options)
    when 'reader'
      reader_episodes(options[:episode], options)
    else
      '' #Episode.all.active.limit(5)
    end
  end
  
  def latest_episodes(episodes, options)
    str = ''
    episodes.each do |episode|
      str << '<div class="col-md-6 col-sm-12">'
      str << '<div class="comicLatest">'
      str << episode_item(episode, options)
      str << '</div>'
      str << '</div>'
    end
    
    raw(str)
  end

  def popular_episodes(episodes, options)
    str = ''
    episodes.each do |episode|
      str << '<div class="col-md-15 col-xs-12">'
      str << '<div class="comicBox">'
      str << episode_item(episode, options)
      str << '</div>'
      str << '</div>'
    end
    
    raw(str)
  end

  def premium_episodes(episodes, options)
    str = ''
    episodes.each do |episode|
      str << episode_item(episode, options)
    end
    
    raw(str)
  end
  
  def reader_episodes(episode, options)
    str = '<div class="row">'
    str << '<div class="col-md-8 col-md-push-2 comic_episodeImgs">'
		str << '<ul id="lightgallery">'
		
		episode.images.order(:sort).each do |image|
  		str << '<li data-src="'
  		str << image.image.url
  		str << '">'
  		str << '<a href="">'
      str << image_tag(raw(image.image.url))
      str << '</a>'
  		str << '</li>'
		end
		
		str << '</ul>'
		str << '</div>'
		str << '</div>'
		
		raw(str)
  end
  
  protected
  
    def episode_item(episode, options)
      img_str = episode_item_img(episode, options)
      str = link_to(raw(img_str), catalogs_comic_episode_url(episode: episode.url_name), class: 'thumbLink')
      str << raw(episode_item_info(episode, options))
      str
    end
    
    def episode_item_img(episode, options)
      str = '<div class="thumb-overlay"></div>'
      image_url = case options[:mode]
                  when 'latest'
                    episode.banner_image.url
                  else
                    episode.image.url
                  end
      str << image_tag(image_url, class: "img-responsive")
      str
    end

    def episode_item_info(episode, options)
      str = '<div class="infoText">'
  		str << '<div class="genre"><small>'
  		str << episode.comic.category_name
  		str << '</small></div>'
  		comic_title = '<div class="comicTitle">'
  		comic_title << episode.comic.name
  		comic_title << '</div>'
  		str << link_to(raw(comic_title), catalogs_comic_episode_url(episode: episode.url_name))
  		str << '<div class="creatorName">Alex Irzaqi</div>'
  		str << '</div>'
  		str
    end
    
    def old_episode_item(episode, options)
      str = '<div class="'
      str << options[:class]
      str << '">'

      str << '<div class="comicBox">'
      str << link_to((image_tag(episode.image.url, class: "img-responsive img-hover") + episode.name), catalogs_comic_episode_url(episode: episode.url_name))
      
      str << '<div class="infoText">'
      str << '<div class="comicTitle">'
      str << episode.comic.name
      str << '</div>'
      
      str << '<div class="creatorName">'
      str << 'Creator Name' # TODO
      str << '</div>'
      
      if episode.comic.category
        str << '<div class="genre">'
        str << episode.comic.category.name
        str << '</div'
      end
      
      str << '</div>'
      <<-STR
          # <a href="/pages/comic">
          #   <img class="img-responsive img-hover" src="http://placehold.it/300x300" alt="">
          #   ep. #1
          # </a>
      		<div class="infoText">
      			<div class="comicTitle">Comic Title</div>
      			<div class="creatorName">Creator Name</div>
      			<div class="genre">Genre</div>
      		</div>
      STR
      str << '</div></div>'
      str
    end
end

app/views/episodes/_form_upload.html.erb
<a name="images"></a> 

<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE TABLE PORTLET-->
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-camera"></i>Images
				</div>
				<div class="tools">
				  <a class="fullscreen" href="javascript:;" data-original-title="" title=""></a>
     			<a href="javascript:;" class="collapse"></a>
				</div>
			</div>
			<!-- BEGIN SAMPLE TABLE PORTLET BODY-->
			<div class="portlet-body">
				<div class="table-scrollable">
				  <%= form_tag admin_contents_comic_episode_images_url(episode_id: params[:id]), role: 'form', method: 'post', multipart: true, class: 'form-horizontal', id: 'fileupload', name: 'fileupload' do %>      
				     
          	<div class="form-body">
            	<div class="form-group form-md-line-input">	
          			<!-- The table listing the files available for upload/download -->
          			<table role="presentation" class="table table-striped clearfix">
            			<tbody class="files">
            			  <% @episode.images.order(:sort).each do |image| %>
            			  <%= hidden_field_tag "episode[sort][#{image.id}][old]", image.sort %>
    							  <tr>
                    <tr class="fade in">
      								<td class="col-md-1"><%= text_field_tag "episode[sort][#{image.id}][new]", image.sort, class: 'form-control-size', placeholder: 'Sort #', size: 3, maxlength: 3 %></td>
                      <td>
                        <span class="preview">
                          <%= link_to image_tag(image.image.url(:thumb)), image.image.url, title: image.image_file_name, download: image.image_file_name, 'data-gallery' => 'data-gallery' %>
                        </span>
                      </td>
                      <td class="col-md-3">
                        <p class="name"><%= image.image_file_name %></p>
                      </td>
                      <td class="col-md-3">
                        <p class="size"><%= number_to_human_size(image.image_file_size, {precision: 5}) %></p>
                      </td>
                      <!--td><span style="height:100px; width:200px; display:block; overflow:auto;">&nbsp;</span></td-->
                      <td>
                        <!--button class="btn red delete btn-sm" data-type="<%= image.image_content_type %>" data-url="<%= admin_contents_comic_episode_image_url(episode_id: params[:id], id: image.id) %>">
                            <i class="fa fa-trash-o"></i>
                            <span>Delete</span>
                        </button-->
                        <%= link_to raw('<i class="fa fa-trash-o"> <span>Delete</span></i>'), admin_contents_comic_episode_image_url(episode_id: params[:id], id: image.id), class: "btn red delete btn-sm", method: :delete, data: { confirm: "Are you sure you want to delete this image?" }, 'data-type' => image.image_content_type %>
                        <!--input type="checkbox" name="delete" value="1" class="toggle">
                        <button class="btn yellow cancel btn-sm">
                            <i class="fa fa-ban"></i>
                            <span>Cancel</span>
                        </button-->
                      </td>
                    </tr>
                    <% end %>
            			</tbody>
          			</table>
          		</div>
          	</div>

            <div class="form-body">
            	<div class="form-group form-md-line-input">
            		<!--div class="col-md-12"-->
            	  <label class="col-md-3 control-label" for="form_control_1">Images Upload</label>
             		<div class="col-md-9 fileinput fileinput-new" data-provides="fileinput">
            			<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            			<div class="row fileupload-buttonbar">
            				<div class="col-lg-7">
            					<!-- The fileinput-button span is used to style the file input field as button -->
            					<span class="btn green fileinput-button">
            					  <i class="fa fa-plus"></i>
            						<span>Add files... </span>
            						<input type="file" name="image" multiple="">
            					</span>
            					<button type="submit" class="btn blue start">
            						<i class="fa fa-upload"></i>
            						<span>Start upload </span>
            					</button>
            					<button type="reset" class="btn warning cancel">
            						<i class="fa fa-ban-circle"></i>
            						<span>Cancel upload </span>
            					</button>
            					<%= link_to 'Sort', '#', class: "btn btn-default", onclick: raw("javascript: fileupload.action='#{sort_admin_contents_comic_episode_images_url(episode_id: params[:id])}'; fileupload.submit();") %>
            					<!--button type="button" class="btn red delete">
            						<i class="fa fa-trash"></i>
            						<span>Delete </span>
            					</button>
            					<input type="checkbox" class="toggle"-->
            					<!-- The global file processing state -->
            					<span class="fileupload-process"></span>
            				</div>
            				<!-- The global progress information -->
            				<div class="col-lg-5 fileupload-progress fade">
            					<!-- The global progress bar -->
            					<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            						<div class="progress-bar progress-bar-success" style="width:0%;"></div>
            					</div>
            					<!-- The extended global progress information -->
            					<div class="progress-extended">&nbsp;</div>
            				</div>
            			</div>
            		</div>
            	</div>

          </div>
        	
          <% end %>
        </div>
			</div>
			<!-- END SAMPLE TABLE PORTLET BODY-->
		</div>
		<!-- END SAMPLE TABLE PORTLET-->
	</div>
</div>
<!-- END PAGE CONTENT-->

<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-start-slideshow="true">
	<div class="slides">
	</div>
	<h3 class="title"></h3>
	<a class="prev">
	‹ </a>
	<a class="next">
	› </a>
	<a class="close white">
	</a>
	<a class="play-pause">
	</a>
	<ol class="indicator">
	</ol>
</div>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="col-md-1">&nbsp;</td>        
        <td>
            <span class="preview"></span>
        </td>
        <td class="col-md-3">
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger label label-danger"></strong>
        </td>
        <td class="col-md-3">
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn blue start" disabled>
                    <i class="fa fa-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn red cancel">
                    <i class="fa fa-ban"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade">
            <input type="hidden" name="episode[sort][{%=file.image_id%}][old]" id="episode_sort_{%=file.image_id%}_old" value="{%=file.sort%}">
            <td class="col-md-1"><input type="text" name="episode[sort][{%=file.image_id%}][new]" id="episode_sort_{%=file.image_id%}_new" value="{%=file.sort%}" class="form-control-size" placeholder="Sort #" size="3" maxlength="3"></td>
            <td>
                <span class="preview">                
                    {% if (file.thumbnail_url) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery="data-gallery" ><img src="{%=file.thumbnail_url%}"/></a>
                    {% } %}
                </span>
            </td>
            <td class="col-md-3">
                <p class="name">
                    {% if (false && file.url) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnail_url?'data-gallery':''%}>{%=file.name%}</a>
                    {% } else { %}
                        <span>{%=file.name%}</span>
                    {% } %}
                </p>
                {% if (file.error) { %}
                    <!--div><span class="label label-danger">Error</span> {%=file.error%}</div-->
                {% } %}
            </td>
            <td class="col-md-3">
                <span class="size">{%=o.formatFileSize(file.size)%}</span>
            </td>
            <td>
                {% if (file.delete_url) { %}
                    <!--button class="btn red delete btn-sm" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                        <i class="fa fa-trash-o"></i>
                        <span>Delete</span>
                    </button-->
                    <%= link_to raw('<i class="fa fa-trash-o"> <span>Delete</span></i>'), "{%=file.delete_url%}", class: "btn red delete btn-sm", method: :delete, data: { confirm: "Are you sure you want to delete this image?" }, 'data-type' => "{%=file.delete_type%}" %>
                    <!--input type="checkbox" name="delete" value="1" class="toggle"-->
                {% } else { %}
                    <button class="btn yellow cancel btn-sm">
                        <i class="fa fa-ban"></i>
                        <span>Cancel</span>
                    </button>
                {% } %}
            </td>
        </tr>
    {% } %}
</script>

app/views/episodes/_header.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li><i class="fa fa-home"></i>Home<i class="fa fa-angle-right"></i></li>
		<li>Contents<i class="fa fa-angle-right"></i></li>
		<li>Comics
		<% breadcrumbs.each do |b| %>
		  <i class="fa fa-angle-right"></i></li>
		  <li><%= b %>
		<% end if breadcrumbs %>
		</li>
	</ul>
</div>
<!-- END PAGE HEADER-->
<br />

<%= render partial: 'layouts/messages' %>

app/views/episodes/edit.html.erb
<%= render partial: 'episodes/header', locals: {breadcrumbs: [link_to(raw("<b>#{@comic.name}</b>"), edit_admin_contents_comic_url(id: @comic.id), class: "btn btn-default"), link_to(raw('<b>Episodes</b>'), admin_contents_comic_episodes_url(@comic.id), class: "btn btn-default"), @episode.name]} %>

<%= form_for @episode, {url: admin_contents_comic_episode_url, role: 'form', method: 'put', multipart: true, html: {class: 'form-horizontal'}} do |f| %>

<div class="row">
  <div class="col-md-offset-9 col-md-3">
    <%= button_tag 'Update', type: 'submit', class: "btn btn-default green" %>
    <%= button_tag 'Reset', class: "btn btn-default", type: 'reset' %>
  </div>
</div>

<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet">
			<div class="portlet-body form">
          
          <%= render partial: 'form', locals: {f: f} %>
          
<% end %>

          <%= render partial: 'form_upload' %>
          
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>
<!-- END PAGE CONTENT-->

app/views/episodes/index.html.erb
    <%= render partial: 'episodes/header', locals: {breadcrumbs: [link_to(raw("<b>#{@comic.name}</b>"), edit_admin_contents_comic_url(id: @comic.id), class: "btn btn-default"), 'Episodes']} %>
    
    <%= form_tag  sort_admin_contents_comic_episodes_url, {role: 'form', method: 'post'} do |f| %>
    
		<div class="row">
      <div class="col-md-offset-9 col-md-3">
        <%= link_to 'Add', new_admin_contents_comic_episode_url, alt: "Add", class: "btn btn-primary green" %>
        <%= button_tag 'Sort', type: 'submit', class: "btn btn-default" %>
      </div>
    </div>
    
    <!-- BEGIN PAGE CONTENT-->
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN SAMPLE TABLE PORTLET-->
				<div class="portlet">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-space-shuttle"></i>Episodes
						</div>
						<div class="tools">
						  <a class="fullscreen" href="javascript:;" data-original-title="" title=""></a>
         			<a href="javascript:;" class="collapse"></a>
						</div>
					</div>
					<div class="portlet-body">
						<div class="table-scrollable">
							<table class="table table-striped table-bordered table-advance table-hover">
							<thead>
							<tr>
								<th class="col-md-1"><i class="fa fa-sort"></i> Sort</th>
								<th><i class="fa fa-photo"></i> Image</th>
								<th><i class="fa fa-photo"></i> Banner Image</th>
								<th><i class="fa fa-info"></i> Name</th>
								<!--th><i class="fa fa-reorder"></i> Details</th-->
								<th><i class="fa fa-plus-square-o"></i> Images</th>
								<th class="col-md-3">&nbsp;</th>
							</tr>
							</thead>
							<tbody>
							  <% @episodes.each do |episode| %>
							  <%= hidden_field_tag "episode[sort][#{episode.id}][old]", episode.sort %>
							  <tr>
  								<td class="col-md-1"><%= text_field_tag "episode[sort][#{episode.id}][new]", episode.sort, class: 'form-control-size', placeholder: 'Sort #', size: 3, maxlength: 3 %></td>
  								<td><%= image_tag episode.image.url(:small) %></td>
  								<td><%= image_tag episode.banner_image.url(:small) %></td>
                  <td><%= episode.name %></td>
                  <!--td><%= episode.details %></td-->
                  <td><%= episode.images.size %></td>
                  <td class="col-md-3">
                    <%= link_to raw('<i class="icon-pencil"> Edit</i>'), edit_admin_contents_comic_episode_url(id: episode.id), class: "btn btn-warning btn-xs" %>
                    <%= link_to raw('<i class="icon-trash"> Delete</i>'), admin_contents_comic_episode_url(id: episode.id), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure you want to delete this episode?" } %>
                  </td>
  							</tr>
							  <% end %>
							</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- END SAMPLE TABLE PORTLET-->
			</div>
		</div>
		<!-- END PAGE CONTENT-->
		
		<% end %>

app/views/episodes/new.html.erb
<%= render partial: 'episodes/header', locals: {breadcrumbs: [link_to(raw("<b>#{@comic.name}</b>"), edit_admin_contents_comic_url(id: @comic.id), class: "btn btn-default"), link_to(raw('<b>Episodes</b>'), admin_contents_comic_episodes_url(@comic.id), class: "btn btn-default"), "New"]} %>

<%= form_for @episode, {url: admin_contents_comic_episodes_url, role: 'form', method: 'post', multipart: true, html: {class: 'form-horizontal', id: 'fileupload'}} do |f| %>

<div class="row">
  <div class="col-md-offset-9 col-md-3">
    <%= button_tag 'Create', type: 'submit', class: "btn btn-default green" %>
    <%= button_tag 'Reset', class: "btn btn-default", type: 'reset' %>
  </div>
</div>

<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet">
			<div class="portlet-body form">
          
          <%= render partial: 'form', locals: {f: f} %>

			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>
<!-- END PAGE CONTENT-->
<% end %>