config/routes.rb
Rails.application.routes.draw do

  
    
  resource :admin, controller: 'admin' do
    
    post 'login', controller: 'admin', action: 'authenticate', on: :collection
    post 'signup', controller: 'admin', action: 'register', on: :collection
    post 'forgot', controller: 'admin', action: 'reset', on: :collection
    
    resource :settings do 
      resource :profiles, except: [:new, :edit, :create, :destroy]
      resources :users
      resources :roles do
        post 'sort', on: :collection
      end
      get ':action', on: :collection, as: 'action'
    end
    
    resource :contents do
      resources :banners do
        post 'sort', on: :collection
      end
      
      resources :comics do
        resources :episodes do
          post 'sort', on: :collection
          resources :images, only: [:create, :destroy] do
            post 'sort', on: :collection
          end
        end
        post 'sort', on: :collection
      end
      
      resources :news do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :galleries do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end
      resources :events do
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
      end

      resources :categories do
        post 'sort', on: :collection
      end
    end

    resource :store, controller: 'store' do
      resources :products do 
        post 'sort', on: :collection
        resources :images, only: [:create, :destroy]
        resources :product_items, as: 'items' do
          post 'sort', on: :collection
        end
      end
      
      resources :orders, except: [:new, :create, :destroy] do
        post 'cancel/:id', on: :collection, action: 'cancel', as: 'cancel'
        post 'revert/:id', on: :collection, action: 'revert', as: 'revert'
        post 'process/:id', on: :collection, action: 'do_process', as: 'process'
        get ':id/:action', on: :collection, as: 'action', id: nil
      end
      
      resources :collections do
        post 'sort', on: :collection
        get ':action', on: :collection, as: 'action'
      end
      
      resources :customers
    end

    resources :tags do
      post 'sort', on: :collection
    end

    resource :mailings do
      resources :campaigns, controller: 'mailing_campaigns'
      resources :lists, controller: 'mailing_lists'
    end
    
    resources :dashboards
        
    
    get ':action', controller: 'admin', on: :collection, as: 'action'
  end  
  
  resource :pages do
    resources :comics
    resources :episodes
  end
  
  post 'mailing_lists/signup', controller: 'mailing_lists', action: 'signup'

  get 'catalogs', controller: 'catalogs', as: 'catalogs_all', action: 'comics'
  get 'catalogs/:comic', controller: 'catalogs', comic: nil, as: 'catalogs_comic', action: 'comic'
  get 'catalogs/episode/:episode', controller: 'catalogs', episode: nil, as: 'catalogs_comic_episode', action: 'episode'
  
  get ':controller/:action/:id'
  
  get '/', controller: 'pages', action: 'show'  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include Sort

  has_many :tag_relations
  has_many :comics, -> { where("tag_relations.content_type = 'Comic'") }, through: :tag_relations
  has_many :products, -> { where("tag_relations.content_type = 'Product'") }, through: :tag_relations
    
  STATUSES = {1 => 'Available',
              2 => 'Retracted',
              3 => 'Hidden'}.freeze
  
  TYPES = {'store'    => 'Store', 
            'content' => 'Content'}.freeze
  
  before_create :initialize_sort!
  
  def status_name
    STATUSES[status_id]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'admin'

  def index
    @tags = Tag.all.order(:sort)
  end
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = 'Tag Create success!'
      redirect_to edit_admin_tag_url(id: @tag.id) and return
    end
    @errors = @tag.errors
    flash[:error] = "We're sorry, we cannot create the tag at the moment"
    render template: 'tags/new'
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update_attributes(tag_params)
      flash[:success] = 'Tag Update success!'
      redirect_to edit_admin_tag_url and return
    end
    @errors = @tag.errors
    flash[:error] = "We're sorry, we cannot update the tag at the moment"
    render template: 'tags/edit'
  end
  
  def destroy
    Tag.find(params[:id]).destroy
    redirect_to admin_tags_url
  end
  
  def sort
    Tag.sort!(params[:tag][:sort])
    flash[:success] = 'Tag Sort success!'
    redirect_to admin_tags_url
  end
  
  protected
    
    def tag_params
      params.require(:tag).permit!
    end
end

app/helpers/tags_helper.rb
module TagsHelper
  def status_options
    Tag::STATUSES.collect {|k,v| [v, k]}
  end
  
  def type_options
    [['All', '']] + Tag::TYPES.collect {|k,v| [v, k]}
  end
  
  def tagging_options
    Tag.all.collect {|t| [t.name, t.id]}
  end
end

app/views/tags/_form.html.erb
<div class="form-body">
	<div class="form-group form-md-line-input<%' has-error' unless @tag.errors[:status_id].blank? %>">  	
		<label class="col-md-2 control-label" for="form_control_1">Status</label>
		<div class="col-md-10">
			<div class="md-radio-inline">
			  <% status_options.each do |name, id| %>
				<div class="md-radio">
					<%= f.radio_button :status_id, id, class: 'md-radiobtn', id: "radio#{id}" %>
					<label for="radio<%= id %>">
					<span></span>
					<span class="check"></span>
					<span class="box"></span>
					<%= name %> </label>
				</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="form-group form-md-line-input<%' has-error' unless @tag.errors[:name].blank? %>">
		<label class="col-md-2 control-label" for="form_control_1">Name</label>
		<div class="col-md-10">
      <%= f.text_field :name, class: "form-control#{' error' unless @tag.errors[:name].blank?}", placeholder: 'Enter Name', id: 'form_control_1' %>			
      <div class="form-control-focus"></div>
		</div>
	</div>
	<div class="form-group form-md-line-input<%' has-error' unless @tag.errors[:tag_type].blank? %>">  	
		<label class="col-md-2 control-label" for="form_control_1">Type</label>
		<div class="col-md-10">
			<div class="md-radio-inline">
			  <% type_options.each do |name, id| %>
				<div class="md-radio">
					<%= f.radio_button :tag_type, id, class: 'md-radiobtn', id: "radio#{id}" %>
					<label for="radio<%= id %>">
					<span></span>
					<span class="check"></span>
					<span class="box"></span>
					<%= name %> </label>
				</div>
				<% end %>
			</div>
		</div>
	</div>

</div>

app/views/tags/_header.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li><i class="fa fa-home"></i>Home<i class="fa fa-angle-right"></i></li>
		<li>Tags
		<% breadcrumbs.each do |b| %>
		  <i class="fa fa-angle-right"></i></li>
		  <li><%= b %>
		<% end if breadcrumbs %>
		</li>
	</ul>
</div>
<!-- END PAGE HEADER-->
<br />

<%= render partial: 'layouts/messages' %>

app/views/tags/edit.html.erb
<%= render partial: 'tags/header', locals: {breadcrumbs: [@tag.name]} %>

<%= form_for @tag, {url: admin_tag_url, role: 'form', method: 'put', multipart: true, html: {class: 'form-horizontal'}} do |f| %>

<div class="row">
	<div class="col-md-11">
    <%= button_tag 'Update Tag', type: 'submit', class: "btn btn-primary pull-right" %>
  </div>
  <div class="col-md-1">
    <%= button_tag 'Reset', class: "btn btn-default pull-right", type: 'reset' %>
  </div>
</div>

<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet">
			<div class="portlet-body form">
          
          <%= render partial: 'form', locals: {f: f} %>

			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>
<!-- END PAGE CONTENT-->
<% end %>

app/views/tags/index.html.erb
    <%= render partial: 'tags/header', locals: {breadcrumbs: []} %>
    
    <%= form_tag  sort_admin_tags_url, {role: 'form', method: 'post'} do |f| %>
    
    <div class="row">
      <div class="col-md-offset-9 col-md-3">
        <%= link_to 'Add', new_admin_tag_url, alt: "Add", class: "btn btn-primary green" %>
        <%= button_tag 'Sort', type: 'submit', class: "btn btn-default" %>
      </div>
    </div>
    
    <!-- BEGIN PAGE CONTENT-->
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN SAMPLE TABLE PORTLET-->
				<div class="portlet">
					<div class="portlet-title">
						<div class="caption">
							<i class="fa fa-tags"></i>Tags
						</div>
						<div class="tools">
						  <a class="fullscreen" href="javascript:;" data-original-title="" title=""></a>
         			<a href="javascript:;" class="collapse"></a>
						</div>
					</div>
					<div class="portlet-body">
						<div class="table-scrollable">
							<table class="table table-striped table-bordered table-advance table-hover">
							<thead>
							<tr>
								<th class="col-md-1"><i class="fa fa-sort"></i> Sort</th>
								<th><i class="fa fa-info"></i> Name</th>
								<th><i class="fa fa-question"></i> Status</th>
								<th class="col-md-2">&nbsp;</th>
							</tr>
							</thead>
							<tbody>
							  <% @tags.each do |tag| %>
							  <%= hidden_field_tag "tag[sort][#{tag.id}][old]", tag.sort %>
							  <tr>
  								<td class="col-md-1"><%= text_field_tag "tag[sort][#{tag.id}][new]", tag.sort, class: 'form-control-size', placeholder: 'Sort #', size: 3, maxlength: 3 %></td>
                  <td><%= tag.name %></td>
                  <td><%= tag.status_name %>
                  <td class="col-md-2">
                    <%= link_to raw('<i class="icon-pencil"> Edit</i>'), edit_admin_tag_url(id: tag.id), class: "btn btn-warning btn-xs" %>
                    <%= link_to raw('<i class="icon-trash"> Delete</i>'), admin_tag_url(id: tag.id), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure you want to delete this tag?" } %>
                  </td>
  							</tr>
							  <% end %>
							</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- END SAMPLE TABLE PORTLET-->
			</div>
		</div>
		<!-- END PAGE CONTENT-->
		<% end %>

app/views/tags/new.html.erb
  <%= render partial: 'tags/header', locals: {breadcrumbs: ["New"]} %>

  <%= form_for @tag, {url: admin_tags_url, role: 'form', method: 'post', multipart: true, html: {class: 'form-horizontal'}} do |f| %>

  <div class="row">
		<div class="col-md-11">
      <%= button_tag 'Create Tag', type: 'submit', class: "btn btn-primary pull-right" %>
    </div>
    <div class="col-md-1">
      <%= button_tag 'Reset', class: "btn btn-default pull-right", type: 'reset' %>
    </div>
  </div>
  
  <!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet">
				<div class="portlet-body form">
            
            <%= render partial: 'form', locals: {f: f} %>

				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
  <!-- END PAGE CONTENT-->
	<% end %>